/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2019-06-30 13:54:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.nio.file.Paths;
import java.nio.file.Files;
import javax.script.Invocable;
import java.nio.charset.StandardCharsets;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import service.UserIO;
import java.util.List;
import entities.User;
import misc.IP_Functions;
import java.util.Date;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entities.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("javax.script.Invocable");
    _jspx_imports_classes.add("java.nio.file.Paths");
    _jspx_imports_classes.add("java.nio.file.Files");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("javax.script.ScriptEngine");
    _jspx_imports_classes.add("javax.script.ScriptEngineManager");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
    _jspx_imports_classes.add("service.UserIO");
    _jspx_imports_classes.add("misc.IP_Functions");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <script src=\"javascript/scripts.js\" type=\"text/javascript\"></script>\n");
      out.write("        <title>Find A Residence - Home</title>\t\n");
      out.write("    </head>\n");
      out.write("    <body> \n");
      out.write("        <div class=\"onepcssgrid-1200\">\n");
      out.write("            <div class=\"onerow\">\n");
      out.write("                <div class=\"col5\">\n");
      out.write("                    <a href=\"index.jsp\"><img src=\"images/far.png\" alt=\"logo\"/></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col7 last\">\n");
      out.write("                    ");

                        User user = (User) session.getAttribute("user");
                        if (user == null) {
                    
      out.write("\n");
      out.write("                    <div id='cssmenu'>\n");
      out.write("                        <ul>\n");
      out.write("                            <li><a href='register.jsp'>Sign up</a></li>\n");
      out.write("                            <li onclick=\"popup('login')\"><a href='#'>Login</a></li>\n");
      out.write("                            <li><a href='search.jsp'>Property Search</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    ");
} else {
      out.write("\n");
      out.write("                    <div id='cssmenu'>\n");
      out.write("                        <ul>\n");
      out.write("                            <li><a href='#'>");
      out.print(user.getName());
      out.write("</a>\n");
      out.write("                                <ul>\n");
      out.write("                                    ");
if (user.isLessor() || user.isSeller()) {
      out.write("\n");
      out.write("                                    <li><a href='myproperties.jsp'>My Properties</a></li> ");
}
      out.write("\n");
      out.write("                                    <li><a href='editprofile.jsp'>Edit Profile</a></li>\n");
      out.write("                                    <li><a href='logout.jsp'>LOGOUT</a></li>\n");
      out.write("                                </ul></li>\n");
      out.write("                                ");
if (user.isLessor() || user.isSeller()) {
      out.write("\n");
      out.write("                            <li><a href='addproperty.jsp'>Property Registration</a></li>\n");
      out.write("                                ");
}
      out.write("\n");
      out.write("                            <li><a href='search.jsp'>Property Search</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    ");
}
      out.write("          \n");
      out.write("                </div>\n");
      out.write("                <div id=\"blanket\" style=\"display:none\" onclick=\"popup('login')\"></div>\n");
      out.write("                <div id=\"login\" style=\"display:none\" >\n");
      out.write("                    <button type=\"button\" onclick=\"popup('login')\">x</button>\n");
      out.write("                    <form id=\"login-form\" action=\"login\" method=\"POST\">\n");
      out.write("                        <input type=\"text\" placeholder=\"Username\" name=\"username\"/>\n");
      out.write("                        <input type=\"password\" placeholder=\"Code\" name=\"password\" />\n");
      out.write("                        <input type=\"submit\" value=\"Connection\" />\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"onerow\">\n");
      out.write("                <div class=\"col12 last\">\n");
      out.write("                    <div style=\"overflow: hidden; padding-top:25px;\" >\n");
      out.write("                        <figure id=\"slidy\">\n");
      out.write("                            <img src=\"images/slider/slide1.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide2.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide3.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide4.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide5.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide6.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide7.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide8.jpg\" alt/>\n");
      out.write("                            <img src=\"images/slider/slide9.jpg\" alt/>\n");
      out.write("                        </figure>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"onerow\">\n");
      out.write("                <div class=\"col1\">             \n");
      out.write("                    <a href=\"index.jsp\"><img src=\"images/farfooter.png\" alt=\"logo\"/></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col3\"><p><b>Find A Residence &copy;</b><br>Support for Rent / Purchase Decisions</p></div>\n");
      out.write("                <div class=\"col4\">             \n");
      out.write("                    <p><b>Powered by:</b><br/>Infoideal technologies - 9812345648<br/>Office- 9812345648</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col4 last\">             \n");
      out.write("                    <p><a href=\"mailto:akashwaghmare54@gmail.com?Subject=Find A Residence\" target=\"_top\">Contact us</a></p>\n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("        </div>\n");
      out.write("        <script>\n");
      out.write("            var timeOnSlide = 3,\n");
      out.write("                    timeBetweenSlides = 1.5,\n");
      out.write("                    animationstring = 'animation',\n");
      out.write("                    animation = false,\n");
      out.write("                    keyframeprefix = '',\n");
      out.write("                    domPrefixes = 'Webkit Moz O Khtml'.split(' '),\n");
      out.write("                    pfx = '',\n");
      out.write("                    slidy = document.getElementById(\"slidy\");\n");
      out.write("            if (slidy.style.animationName !== undefined) {\n");
      out.write("                animation = true;\n");
      out.write("            }\n");
      out.write("            if (animation === false) {\n");
      out.write("                for (var i = 0; i < domPrefixes.length; i++) {\n");
      out.write("                    if (slidy.style[ domPrefixes[i] + 'AnimationName' ] !== undefined) {\n");
      out.write("                        pfx = domPrefixes[ i ];\n");
      out.write("                        animationstring = pfx + 'Animation';\n");
      out.write("                        keyframeprefix = '-' + pfx.toLowerCase() + '-';\n");
      out.write("                        animation = true;\n");
      out.write("                        break;\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if (animation === false) {\n");
      out.write("                // animate using a JavaScript fallback, if you wish\n");
      out.write("            } else {\n");
      out.write("                var images = slidy.getElementsByTagName(\"img\"),\n");
      out.write("                        firstImg = images[0],\n");
      out.write("                        imgWrap = firstImg.cloneNode(false);\n");
      out.write("                slidy.appendChild(imgWrap);\n");
      out.write("                var imgCount = images.length,\n");
      out.write("                        totalTime = (timeOnSlide + timeBetweenSlides) * (imgCount - 1),\n");
      out.write("                        slideRatio = (timeOnSlide / totalTime) * 100,\n");
      out.write("                        moveRatio = (timeBetweenSlides / totalTime) * 100,\n");
      out.write("                        basePercentage = 100 / imgCount,\n");
      out.write("                        position = 0,\n");
      out.write("                        css = document.createElement(\"style\");\n");
      out.write("                css.type = \"text/css\";\n");
      out.write("                css.innerHTML += \"#slidy { text-align: left; margin: 0; font-size: 0; position: relative; width: \" + (imgCount * 100) + \"%;  }\";\n");
      out.write("                css.innerHTML += \"#slidy img { float: left; width: \" + basePercentage + \"%; }\";\n");
      out.write("                css.innerHTML += \"@\" + keyframeprefix + \"keyframes slidy {\";\n");
      out.write("                for (i = 0; i < (imgCount - 1); i++) {\n");
      out.write("                    position += slideRatio;\n");
      out.write("                    css.innerHTML += position + \"% { left: -\" + (i * 100) + \"%; }\";\n");
      out.write("                    position += moveRatio;\n");
      out.write("                    css.innerHTML += position + \"% { left: -\" + ((i + 1) * 100) + \"%; }\";\n");
      out.write("                }\n");
      out.write("                css.innerHTML += \"}\";\n");
      out.write("                css.innerHTML += \"#slidy { left: 0%; \" + keyframeprefix + \"transform: translate3d(0,0,0); \" + keyframeprefix + \"animation: \" + totalTime + \"s slidy infinite; }\";\n");
      out.write("                document.body.appendChild(css);\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
