/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2019-06-30 14:06:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entities.User;
import java.util.Locale;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entities.User");
    _jspx_imports_classes.add("java.util.Locale");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\t\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\n");
      out.write("        <script src=\"javascript/scripts.js\" type=\"text/javascript\"></script>\n");
      out.write("        <title>Find A Residence - New User Registration</title>\t\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

            User user = (User) session.getAttribute("user");
            if (user != null) {
                response.sendRedirect("index.jsp");
            }
        
      out.write("\n");
      out.write("        <div class=\"onepcssgrid-1200\">\n");
      out.write("            <div class=\"onerow\">\n");
      out.write("                <div class=\"col5\">\n");
      out.write("                    <a href=\"index.jsp\"><img src=\"images/far.png\" alt=\"logo\"/></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col7 last\">\n");
      out.write("                    <div id='cssmenu'>\n");
      out.write("                        <ul>\n");
      out.write("                            <li><a href='register.jsp'>Sign up</a></li>\n");
      out.write("                            <li onclick=\"popup('login')\"><a href='#'>Login</a></li>\n");
      out.write("                            <li><a href='search.jsp'>Property Search</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"blanket\" style=\"display:none\" onclick=\"popup('login')\"></div>\n");
      out.write("                <div id=\"login\" style=\"display:none;\">\n");
      out.write("                    <button type=\"button\" onclick=\"popup('login')\">x</button>\n");
      out.write("                    <form id=\"login-form\" action=\"login\">\n");
      out.write("                        <input type=\"text\" placeholder=\"Username\" name=\"username\"/>\n");
      out.write("                        <input type=\"password\" placeholder=\"Password\" name=\"password\" />\n");
      out.write("                        <input type=\"submit\" value=\"Login\" />\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"onerow\">\n");
      out.write("                <div class=\"col12 last\">\n");
      out.write("                    <h1>New User Registration</h1>\n");
      out.write("                    <form autocomplete=\"off\" name=\"register-form\" id=\"general-form\" action=\"registration\" onsubmit=\"return validateRegisterForm()\" method=\"POST\">\n");
      out.write("                        <p class=\"general\"><label for=\"username\">Username <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"username\" type=\"text\" name=\"username\" placeholder=\"user\"/>\n");
      out.write("                        <p class=\"general\"><label for=\"password\">Password <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"password\" type=\"password\" name=\"password\"  />\n");
      out.write("                        <p class=\"general\"><label for=\"password2\">Confirm Password <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"password2\" type=\"password\" name=\"password2\"  />\n");
      out.write("                        <p class=\"general\"><label for=\"email\">Email <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"email\" type=\"email\" name=\"email\"  placeholder=\"Email\"/>\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"name\">Name <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"name\" type=\"text\" name=\"name\" placeholder=\"Name\"/>\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"middle_name\">Middle name\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"middle_name\" type=\"text\" name=\"middle_name\" placeholder=\"Middle name\"/>\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"surname\">Last name <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"surname\" type=\"text\" name=\"surname\" placeholder=\"Last name\"/>\n");
      out.write("                        <fieldset>\n");
      out.write("                            <label for=\"lessor\">Lessor\n");
      out.write("                            </label>\n");
      out.write("                            <input id=\"lessor\" type=\"checkbox\" value=\"1\" name=\"lessor\" />\n");
      out.write("\n");
      out.write("                            <label for=\"seller\">Seller\n");
      out.write("                            </label>\n");
      out.write("                            <input id=\"seller\" type=\"checkbox\" value=\"1\" name=\"seller\" />\n");
      out.write("\n");
      out.write("                            <label for=\"lessee\">Tenant\n");
      out.write("                            </label>\n");
      out.write("                            <input id=\"lessee\" type=\"checkbox\" value=\"1\" name=\"lessee\" />\n");
      out.write("\n");
      out.write("                            <label for=\"buyer\">Buyer\n");
      out.write("                            </label>\n");
      out.write("                            <input id=\"buyer\" type=\"checkbox\" value=\"1\" name=\"buyer\" />\n");
      out.write("                        </fieldset>\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"telephone1\" > Phone\n");
      out.write("                            </label> </p>\n");
      out.write("                        <input id=\"telephone1\"  type=\"text\" name=\"telephone1\" placeholder=\"9876543210\" />\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"telephone_2\" > Phone 2\n");
      out.write("                            </label> </p>\n");
      out.write("                        <input id=\"telephone_2\"  type=\"text\" name=\"telephone_2\"  placeholder=\"9876543210\" />\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"fax\" > FAX\n");
      out.write("                            </label> </p>\n");
      out.write("                        <input id=\"fax\"  type=\"text\" name=\"fax\"  />\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"address1\" > Address 1 <font color=\"red\">*</font>\n");
      out.write("                            </label> </p>\n");
      out.write("                        <input id=\"address1\"  type=\"text\" name=\"address1\"  placeholder=\"Address 1\"/>\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"address2\"> Address 2 \n");
      out.write("                            </label> </p>\n");
      out.write("                        <input id=\"address2\" type=\"text\" name=\"address2\" />\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"address3\"> Address 3\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"address3\" type=\"text\" name=\"address3\"  />\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"city\"> City <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"city\" type=\"text\" name=\"city\" placeholder=\"City\"/>\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"region\"> Area <font color=\"red\">*</font>\n");
      out.write("                            </label></p> \n");
      out.write("                        <input id=\"region\" type=\"text\" name=\"region\" placeholder=\"Area\"/>\n");
      out.write("                        <p class=\"general\">\n");
      out.write("                            <label for=\"postalCode\"> Postcodes <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                        <input id=\"postalCode\" type=\"text\" name=\"postalCode\" placeholder=\"411043\"/>\n");
      out.write("                        <p class=\"general\"><label for=\"country\"> Country <font color=\"red\">*</font>\n");
      out.write("                            </label></p>\n");
      out.write("                            ");
 String[] locales = Locale.getISOCountries(); 
      out.write("\n");
      out.write("                        <select id=\"country\" name=\"country\">\n");
      out.write("                            ");

                                for (String locale : locales) {
                                    Locale _locale = new Locale("", locale);
                                    if (_locale.getDisplayCountry().equals("India")) {
                                        out.println("<option selected value=\"" + _locale.getDisplayCountry() + "\">" + _locale.getDisplayCountry() + "</option>");
                                    } else {
                                        out.println("<option value=\"" + _locale.getDisplayCountry() + "\">" + _locale.getDisplayCountry() + "</option>");
                                    }
                                }
                            
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                        <p><input class=\"buttom\" name=\"submit\" id=\"submit\" value=\"Submit\" type=\"submit\"> </p>\t \n");
      out.write("                    </form>\n");
      out.write("                    <p>(<font color=\"red\">*</font> Compulsory field)</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"onerow\">\n");
      out.write("                <div class=\"col1\">             \n");
      out.write("                    <a href=\"index.jsp\"><img src=\"images/farfooter.png\" alt=\"logo\"/></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col3\"><p><b>Find A Residence &copy;</b><br>Support for Rent / Purchase Decisions</p></div>\n");
      out.write("                <div class=\"col4\">             \n");
      out.write("                    <p><b>Powered by:</b><br/>Infoideal technologies - 9812345648<br/>Office- 9812345648</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col4 last\">             \n");
      out.write("                    <p><a href=\"mailto:akashwaghmare54@gmail.com?Subject=Find A Residence\" target=\"_top\">Contact us</a></p>\n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("        </div> \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
