SELECT * FROM SPLDATA.CO_PTMST WHERE PT_PRTCD ='S8888';
UPDATE SHNDATA.CO_PTMST SET PT_STSFL ='X' WHERE PT_PRTCD ='S8888' AND PT_PRTTP ='G';

COMMIT;

SELECT * FROM SPLDATA.CO_PTMST WHERE PT_PRTCD IN('S0839','S0873');

SELECT * FROM SHNDATA.CO_PTMST WHERE PT_PRTCD ='S0840';

UPDATE SHNDATA.CO_PTMST SET PT_STSFL ='X' WHERE PT_PRTCD ='S0874';
UPDATE SHNDATA.CO_PTMST SET PT_STSFL ='X' WHERE PT_PRTCD ='S0873';
UPDATE SHNDATA.CO_PTMST SET PT_STSFL ='X' WHERE PT_PRTCD ='S8888' AND PT_PRTTP ='G';

COMMIT;

UPDATE SPLDATA.CO_PTMST SET PT_PRTNM = 'SPL POLYMERS LIMITED' WHERE PT_PRTCD ='S0840';

SELECT IVT_LADNO,IVT_INVNO,IVT_BYRCD FROM SHNDATA.MR_IVTRN WHERE IVT_SALTP ='14' AND IVT_LADNO <> IVT_INVNO ;AND IVT_INVNO LIKE '7512%';;

SELECT IVT_LADNO,IVT_INVNO,IVT_BYRCD FROM SHNDATA.MR_IVTRN WHERE IVT_SALTP ='14' AND IVT_LADNO <> IVT_INVNO AND IVT_INVNO LIKE '7514%';;

UPDATE SHNDATA.MR_IVTRN SET IVT_LADNO = IVT_INVNO WHERE IVT_SALTP ='14' AND IVT_LADNO <> IVT_INVNO AND IVT_INVNO LIKE '7514%';

COMMIT;


SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_SALTP ='14' AND IVT_LADNO <> IVT_INVNO ;
SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_SALTP ='14' AND IVT_LADNO IN ('75010004','75010012');

SELECT * FROM SPLDATA.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP ='MR01IND' AND CMT_CODCD ='SDR8';

SELECT * FROM SPLDATA.CO_PTMST WHERE PT_PRTTP ='G';

INSERT INTO SPLTEST.CO_CDTRN SELECT * FROM SPLDATA.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP ='MR01IND' AND CMT_CODCD ='SDR8';

DELETE FROM SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP ='MR01IND' AND CMT_CODCD ='SDR8';
SELECT * FROM SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP ='MR01IND' AND CMT_CODCD ='SDR8';

UPDATE SPLTEST.CO_CDTRN SET CMT_CODCD ='SHA8',CMT_CODDS ='HARITA AGENCIES',CMT_CHP02 = 'H0001',CMT_CCSVL ='0000',CMT_MODLS ='G'  WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP ='MR01IND' AND CMT_CODCD ='SDR8';

COMMIT;

INSERT INTO SHNDATA.CO_CDTRN SELECT * FROM SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP ='MR01IND' AND CMT_CODCD ='SHA8';

INSERT INTO SHNDATA.CO_CDTRN SELECT * FROM SPLDATA.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP ='MR01IND' AND CMT_CODCD ='SBB8';

SELECT * FROM SHNDATA.MR_INMST WHERE IN_BYRCD ='S0873';

SELECT * FROM SHNDATA.MR_INMST WHERE IN_BYRCD ='S0874';

UPDATE SHNDATA.MR_INMST SET IN_BYRCD = 'S0839',IN_CNSCD ='S0839',IN_DSRCD ='S0017' WHERE IN_BYRCD ='S0873';
UPDATE SHNDATA.MR_INMST SET IN_BYRCD = 'S0840',IN_CNSCD ='S0840',IN_DSRCD ='S0016' WHERE IN_BYRCD ='S0874';
COMMIT;

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='S0873';
UPDATE SHNDATA.MR_IVTRN SET IVT_BYRCD ='S0873',IVT_CNSCD ='S0873',IVT_DSRCD ='S0017'  WHERE IVT_BYRCD ='S0873';
UPDATE SHNDATA.MR_IVTR1 SET IVT_BYRCD ='S0873',IVT_CNSCD ='S0873',IVT_DSRCD ='S0017'  WHERE IVT_BYRCD ='S0873';

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='S0873';
UPDATE SHNDATA.MR_IVTRN SET IVT_BYRCD ='S0874',IVT_CNSCD ='S0874',IVT_DSRCD ='S0016'  WHERE IVT_BYRCD ='S0874';
UPDATE SHNDATA.MR_IVTR1 SET IVT_BYRCD ='S0874',IVT_CNSCD ='S0874',IVT_DSRCD ='S0016'  WHERE IVT_BYRCD ='S0874';

SELECT * FROM SHNDATA.MR_PTTRN WHERE PT_PRTCD ='S0874';
UPDATE SHNDATA.MR_PLTRN SET PL_PRTCD ='S0840' WHERE PL_PRTCD ='S0874';

SELECT * FROM SHNDATA.MR_INMST WHERE IN_BYRCD ='S0840' AND IN_CNSCD ='S0874';
UPDATE SHNDATA.MR_INMST SET IN_CNSCD = 'S0840' WHERE IN_BYRCD ='S0840' AND IN_CNSCD ='S0874';

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='S0840' AND IVT_CNSCD ='S0874';
UPDATE SHNDATA.MR_IVTRN SET IVT_CNSCD = 'S0840' WHERE IVT_BYRCD ='S0840' AND IVT_CNSCD ='S0874';
UPDATE SHNDATA.MR_IVTR1 SET IVT_CNSCD = 'S0840' WHERE IVT_BYRCD ='S0840' AND IVT_CNSCD ='S0874';

UPDATE SHNDATA.MR_IVTRN SET IVT_CNSCD = 'S0839' WHERE IVT_BYRCD ='S0839' AND IVT_CNSCD ='S0873';
UPDATE SHNDATA.MR_IVTR1 SET IVT_CNSCD = 'S0839' WHERE IVT_BYRCD ='S0839' AND IVT_CNSCD ='S0873';

COMMIT;

SELECT * FROM SHNDATA.MR_INMST WHERE IN_DSRCD ='H0001';
SELECT DISTINCT IN_SALTP,IN_DSRCD,IN_BYRCD FROM SHNDATA.MR_INMST WHERE IN_DSRCD ='S8888' AND IN_SALTP ='04';

SELECT PT_PRTTP,PT_PRTCD,PT_PRTNM,PT_DSRCD,PT_CNSRF FROM SPLDATA.CO_PTMST WHERE PT_CNSRF ='S8888';

SELECT DISTINCT IVT_DSRCD,IVT_BYRCD FROM SHNDATA.MR_IVTRN WHERE IVT_SALTP ='14' ;

SELECT * FROM SHNDATA.MR_INMST WHERE IN_DSRCD ='S8888' AND IN_SALTP ='04' ;AND IN_BYRCD ='S0836';

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_INDNO ='SDE73168'; ='S8888' AND IN_SALTP ='04';


UPDATE SHNDATA.MR_INMST SET IN_DSRCD ='S0017',IN_BYRCD ='S0839',IN_CNSCD ='S0839' WHERE IN_DSRCD ='S8888' AND IN_SALTP ='04' AND IN_BYRCD ='S0836';

SELECT * FROM SHNDATA.MR_IVTR1 WHERE IVT_DSRCD ='S8888' AND IVT_SALTP ='04';
COMMIT;

SELECT DISTINCT IVT_DSRCD,IVT_BYRCD,IVT_CNSCD FROM SHNDATA.MR_IVTRN WHERE IVT_DSRCD IN('S0016','S0017','H0001') ORDER BY IVT_DSRCD;

DELETE FROM SPLTEST.CO_PTMST;

INSERT INTO SPLTEST.CO_PTMST SELECT * FROM SPLDATA.CO_PTMST;

CREATE TABLE SPLTEST.CO_PTMST LIKE SPLDATA.CO_PTMST;
DROP TABLE SPLTEST.CO_PTMST;
COMMIT;

UPDATE SHNDATA.CO_PTMST SET PT_CNSRF ='' WHERE PT_CNSRF ='S8888' AND PT_PRTTP ='C' ; 

SELECT * FROM SPLDATA.CO_PTMST WHERE PT_CNSRF ='S8888';
SELECT * FROM SHNDATA.CO_PTMST WHERE PT_CNSRF ='S8888';

SELECT * FROM SPLDATA.CO_PTMST WHERE PT_PRTCD ='H0121';
SELECT * FROM SPLDATA.CO_PTMST WHERE PT_PRTTP ='G' ;

SELECT * FROM SPLDATA.MR_INMST WHERE IN_SALTP ='04' AND IN_DSRCD ='W8888';

SELECT * FROM SHNDATA.MR_INMST WHERE IN_SALTP ='04' AND IN_DSRCD ='E8888';

SELECT DISTINCT IVT_INVNO,IVT_INVDT,IVT_BYRCD FROM SHNDATA.MR_IVTRN WHERE IVT_SALTP ='04' AND IVT_INVNO NOT IN(SELECT IVT_INVNO FROM SHNDATA.MR_IVTR1) ORDER BY IVT_INVNO,IVT_INVDT;

insert into shndata.mr_ivtr1(IVT_MKTTP,IVT_LADNO,IVT_PRDCD,IVT_PKGTP,IVT_LADDT,
    IVT_DORNO,IVT_INDNO,IVT_INVNO,IVT_INVDT,IVT_GINNO,IVT_SALTP,IVT_CNSCD,IVT_BYRCD,
    IVT_DSRCD,IVT_TMOCD,IVT_CURCD,IVT_LRYNO,IVT_CNTDS,IVT_LR_NO,IVT_LR_DT,IVT_PMDDT,
    IVT_CPTVL,IVT_ASSVL,IVT_DSCVL,IVT_PKFVL,IVT_INSVL,IVT_STXVL,IVT_EXCVL,IVT_INVVL,
    IVT_NETVL,IVT_LADRT,IVT_EXCRT,IVT_INVRT,IVT_PKGWT,IVT_LADQT,IVT_REQQT,
    IVT_INVQT,IVT_INVPK,IVT_AUTBY,IVT_DSTDS,IVT_STSFL,IVT_LUSBY,IVT_LUPDT,IVT_DTPCD,
    IVT_TSTFL,IVT_SLRFL,IVT_TSLNO,IVT_RSLNO,IVT_ADLNO,IVT_ADLDT,IVT_PRDDS,IVT_PRDTP,
    IVT_LOTRF,IVT_UOMCD,IVT_DORDT,IVT_LODDT,IVT_TRPCD,IVT_PORNO,IVT_PORDT,IVT_ZONCD,
    IVT_PMTTP,IVT_EXCCO,IVT_STXRT,IVT_STXCD,IVT_OCTRT,IVT_OCTCD,IVT_ALODT,IVT_TRNFL,
    IVT_FRTRT,IVT_SVCCD,IVT_SVCRT,IVT_EPIFL,IVT_RSNVL,IVT_CDCVL,IVT_DDCVL,IVT_TDCVL,
    IVT_DCMVL,IVT_TDCRF,IVT_SBSCD,IVT_EDCRT,IVT_EDCVL,IVT_EHCRT,IVT_EHCVL,IVT_SCHRT,
    IVT_TOTRT,IVT_PMTCD,IVT_CC1VL,IVT_CC1RF,IVT_CC2VL,IVT_CC2RF,IVT_CC3VL,IVT_CC3RF,IVT_FRTVL,IVT_CCLVL,
    IVT_COMVL,IVT_SLRQT,IVT_SLRRF,IVR_CRDVL,IVT_CRDVL,IVT_COPVL,IVT_BKGDT,IVT_CPRVL,
    IVT_TD1VL,IVT_TD2VL,IVT_TD3VL,IVT_TDMVL,IVT_LCNUM,IVT_LCDAT,IVT_UNLSQ,IVT_CSLNO,
    IVT_OCRVL,IVT_ODBVL,IVT_DSRTP) select IVT_MKTTP,IVT_LADNO,IVT_PRDCD,IVT_PKGTP,
    IVT_LADDT,IVT_DORNO,IVT_INDNO,IVT_INVNO,IVT_INVDT,IVT_GINNO,IVT_SALTP,IVT_CNSCD,
    IVT_BYRCD,IVT_DSRCD,IVT_TMOCD,IVT_CURCD,IVT_LRYNO,IVT_CNTDS,IVT_LR_NO,IVT_LR_DT,
    IVT_PMDDT,IVT_CPTVL,IVT_ASSVL,IVT_DSCVL,IVT_PKFVL,IVT_INSVL,IVT_STXVL,IVT_EXCVL,
    IVT_INVVL,IVT_NETVL,IVT_LADRT,IVT_EXCRT,IVT_INVRT,IVT_PKGWT,IVT_LADQT,
    IVT_REQQT,IVT_INVQT,IVT_INVPK,IVT_AUTBY,IVT_DSTDS,IVT_STSFL,IVT_LUSBY,IVT_LUPDT,
    IVT_DTPCD,IVT_TSTFL,IVT_SLRFL,IVT_TSLNO,IVT_RSLNO,IVT_ADLNO,IVT_ADLDT,IVT_PRDDS,
    IVT_PRDTP,IVT_LOTRF,IVT_UOMCD,IVT_DORDT,IVT_LODDT,IVT_TRPCD,IVT_PORNO,IVT_PORDT,
    IVT_ZONCD,IVT_PMTTP,IVT_EXCCO,IVT_STXRT,IVT_STXCD,IVT_OCTRT,IVT_OCTCD,IVT_ALODT,
    IVT_TRNFL,IVT_FRTRT,IVT_SVCCD,IVT_SVCRT,IVT_EPIFL,IVT_RSNVL,IVT_CDCVL,IVT_DDCVL,
    IVT_TDCVL,IVT_DCMVL,IVT_TDCRF,IVT_SBSCD,IVT_EDCRT,IVT_EDCVL,IVT_EHCRT,IVT_EHCVL,
    IVT_SCHRT,IVT_TOTRT,IVT_PMTCD,IVT_CC1VL,IVT_CC1RF,IVT_CC2VL,IVT_CC2RF,IVT_CC3VL,IVT_CC3RF,IVT_FRTVL,
    IVT_CCLVL,IVT_COMVL,IVT_SLRQT,IVT_SLRRF,IVR_CRDVL,IVT_CRDVL,IVT_COPVL,IVT_BKGDT,
    IVT_CPRVL,IVT_TD1VL,IVT_TD2VL,IVT_TD3VL,IVT_TDMVL,IVT_LCNUM,IVT_LCDAT,IVT_UNLSQ,
    IVT_CSLNO,IVT_OCRVL,IVT_ODBVL,IVT_DSRTP from sHNdata.mr_ivtrn where ivt_invno = '80000128';

commit;

select ivt_saltp,ivt_invno,ivt_prdds,ivt_invqt,ivt_invrt,ivt_assvl,ivt_netvl,ivt_invvl,ivt_csirf from shndata.mr_ivtrn
where ivt_byrcd ='R0241' and ivt_saltp in('04','14') order by ivt_saltp,ivt_invno;

delete FROM SHNDATA.mr_ivtr1 WHERE ivt_invno = '80000035';

UPDATE SHNDATA.CO_PTMST SET PT_STSFL ='X' WHERE PT_PRTTP ='G' AND PT_PRTCD IN('S8888','N8888','W8888','E8888');


SELECT DISTINCT IN_DSRCD,IN_DSRNM FROM SHNDATA.MR_INMST WHERE IN_SALTP ='04';

SELECT * FROM SHNDATA.MR_PRTRN WHERE PR_PRTCD ='R0241';




SELECT * FROM SHNDATA.MR_PLTRN WHERE PL_PRTCD = 'R0241';
SELECT * FROM SHNDATA.MR_PLTRN WHERE PL_PRTCD = 'R0233';

COMMIT;

DELETE FROM SPLTEST.CO_PTMST WHERE PT_PRTCD ='R0003';

INSERT INTO SPLTEST.CO_PTMST SELECT * FROM SPLDATA.CO_PTMST WHERE PT_PRTCD ='R0003' ;

UPDATE SPLTEST.CO_PTMST SET PT_PRTCD ='R0004',PT_PRTTP ='D' WHERE PT_PRTCD ='R0004' AND PT_PRTTP ='G' ;

COMMIT;

INSERT INTO SPLDATA.CO_PTMST SELECT * FROM SPLTEST.CO_PTMST WHERE PT_PRTCD ='R0004' AND PT_PRTTP ='D' ;
SELECT * FROM SHNDATA.CO_PTMST WHERE PT_PRTCD ='R0004' ;


SELECT * FROM SHNDATA.MR_INMST WHERE IN_BYRCD ='R0233';
SELECT * FROM SHNDATA.MR_INMST WHERE IN_BYRCD ='R0241';

-- CHANGING THE C. STK CODE OF R0241 TO R0004

SELECT * FROM SHNDATA.MR_INMST WHERE IN_BYRCD ='R0241' AND IN_SALTP ='04';
UPDATE SHNDATA.MR_INMST SET IN_DSRCD ='R0004' WHERE IN_BYRCD ='R0241' AND IN_SALTP ='04';
UPDATE SHNDATA.MR_IVTRN SET IVT_DSRCD ='R0004' WHERE IVT_BYRCD ='R0241' AND IVT_SALTP ='04';
UPDATE SHNDATA.MR_IVTR1 SET IVT_DSRCD ='R0004' WHERE IVT_BYRCD ='R0241' AND IVT_SALTP ='04';
UPDATE SHNDATA.MR_IVTRN SET IVT_DSRCD ='R0004' WHERE IVT_BYRCD ='R0241' AND IVT_SALTP ='14';

COMMIT;

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_DSRCD ='S0014';

UPDATE SHNDATA.CO_CDTRN SET CMT_CODCD ='R0004',CMT_CODDS ='RATNA' WHERE CMT_CGMTP ='SYS' AND CMT_CGSTP ='COXXCST' AND CMT_CODCD ='S0014';

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='R0241' AND IVT_SALTP ='14';

SELECT SUBSTRING(IVT_INVNO,5,4) FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='R0241' AND IVT_SALTP ='14';
UPDATE SHNDATA.MR_IVTRN SET IVT_INVNO = '7510' + SUBSTRING(IVT_INVNO,5,4) WHERE IVT_BYRCD ='R0241' AND IVT_SALTP ='14';
UPDATE SHNDATA.MR_PLTRN SET PL_DOCNO = '7510' + SUBSTRING(PL_DOCNO,5,4) WHERE PL_PRTCD ='R0241' AND PL_DOCTP ='21' AND SUBSTRING(PL_DOCNO,3,2) ='09' ;
COMMIT;
UPDATE SHNDATA.MR_IVTRN SET IVT_LADNO  = IVT_INVNO WHERE IVT_BYRCD ='R0241' AND IVT_SALTP ='14';

SELECT * FROM SHNDATA.CO_PTMST WHERE PT_PRTCD ='R0233';

SELECT * FROM SHNDATA.CO_PTMST WHERE PT_PRTCD ='R0241';

SELECT * FROM SHNDATA.CO_PTMST WHERE PT_CNSRF ='R0003';


SELECT IN_DSRCD,IN_INDNO,IN_BYRCD,IN_BYRNM FROM SHNDATA.MR_INMST WHERE IN_SALTP ='04' AND IN_BYRCD ='D0146';

SELECT IN_DSRCD,IN_INDNO,IN_BYRCD,IN_BYRNM FROM SHNDATA.MR_INMST WHERE IN_SALTP ='04' AND IN_BYRCD ='D0147';

UPDATE SHNDATA.MR_INMST SET IN_DSRCD ='D0003' WHERE IN_SALTP ='04' AND IN_BYRCD ='D0147';
UPDATE SHNDATA.MR_INMST SET IN_DSRCD ='D0004' WHERE IN_SALTP ='04' AND IN_BYRCD ='D0150';

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='D0169';
SELECT * FROM SHNDATA.MR_IVTR1 WHERE IVT_BYRCD ='D0169';

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='D0147';
UPDATE SHNDATA.MR_IVTRN SET IVT_DSRCD ='D0003' WHERE IVT_BYRCD ='D0147';
UPDATE SHNDATA.MR_IVTRN SET IVT_DSRCD ='D0004' WHERE IVT_BYRCD ='D0150';

UPDATE SHNDATA.MR_IVTR1 SET IVT_DSRCD ='D0003' WHERE IVT_BYRCD ='D0147';
UPDATE SHNDATA.MR_IVTR1 SET IVT_DSRCD ='D0004' WHERE IVT_BYRCD ='D0150';
COMMIT;

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='D0169' AND IVT_SALTP ='14' AND CONVERT(varchar,IVT_INVDT,101) >='04/01/2007';


SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_BYRCD ='D0146' AND IVT_SALTP ='14' ;

UPDATE SHNDATA.MR_IVTRN SET IVT_INVNO ='7515' + SUBSTRING(IVT_INVNO,5,4) WHERE IVT_BYRCD ='D0146' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_IVTRN SET IVT_LADNO = IVT_INVNO  WHERE IVT_BYRCD ='D0146' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_PLTRN SET PL_DOCNO ='7515' + SUBSTRING(PL_DOCNO,5,4) WHERE PL_PRTCD ='D0146' AND PL_DOCNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PTTRN SET PT_INVNO ='7515' + SUBSTRING(PT_INVNO,5,4) WHERE PT_PRTCD ='D0146' AND PT_INVNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PATRN SET PA_DBTNO ='7515' + SUBSTRING(PA_DBTNO,5,4) WHERE PA_PRTCD ='D0146' AND PA_DBTNO LIKE '7503%' ;

COMMIT;

UPDATE SHNDATA.MR_IVTRN SET IVT_INVNO ='7516' + SUBSTRING(IVT_INVNO,5,4) WHERE IVT_BYRCD ='D0169' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_IVTRN SET IVT_LADNO = IVT_INVNO  WHERE IVT_BYRCD ='D0146' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_PLTRN SET PL_DOCNO ='7516' + SUBSTRING(PL_DOCNO,5,4) WHERE PL_PRTCD ='D0169' AND PL_DOCNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PTTRN SET PT_INVNO ='7516' + SUBSTRING(PT_INVNO,5,4) WHERE PT_PRTCD ='D0169' AND PT_INVNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PATRN SET PA_DBTNO ='7516' + SUBSTRING(PA_DBTNO,5,4) WHERE PA_PRTCD ='D0169' AND PA_DBTNO LIKE '7503%' ;

COMMIT;

UPDATE SHNDATA.MR_IVTRN SET IVT_INVNO ='7517' + SUBSTRING(IVT_INVNO,5,4) WHERE IVT_BYRCD ='D0147' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_IVTRN SET IVT_LADNO = IVT_INVNO  WHERE IVT_BYRCD ='D0147' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_PLTRN SET PL_DOCNO ='7517' + SUBSTRING(PL_DOCNO,5,4) WHERE PL_PRTCD ='D0147' AND PL_DOCNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PTTRN SET PT_INVNO ='7517' + SUBSTRING(PT_INVNO,5,4) WHERE PT_PRTCD ='D0147' AND PT_INVNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PATRN SET PA_DBTNO ='7517' + SUBSTRING(PA_DBTNO,5,4) WHERE PA_PRTCD ='D0147' AND PA_DBTNO LIKE '7503%' ;

COMMIT;

UPDATE SHNDATA.MR_IVTRN SET IVT_INVNO ='7518' + SUBSTRING(IVT_INVNO,5,4) WHERE IVT_BYRCD ='D0150' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_IVTRN SET IVT_LADNO = IVT_INVNO  WHERE IVT_BYRCD ='D0146' AND IVT_SALTP ='14' ;
UPDATE SHNDATA.MR_PLTRN SET PL_DOCNO ='7518' + SUBSTRING(PL_DOCNO,5,4) WHERE PL_PRTCD ='D0150' AND PL_DOCNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PTTRN SET PT_INVNO ='7518' + SUBSTRING(PT_INVNO,5,4) WHERE PT_PRTCD ='D0150' AND PT_INVNO LIKE '7503%' ;
UPDATE SHNDATA.MR_PATRN SET PA_DBTNO ='7518' + SUBSTRING(PA_DBTNO,5,4) WHERE PA_PRTCD ='D0150' AND PA_DBTNO LIKE '7503%' ;

COMMIT;

SELECT * FROM SHNDATA.MR_IVTRN WHERE IVT_SALTP ='04' AND IVT_INVNO NOT IN(SELECT IVT_INVNO FROM SHNDATA.MR_IVTR1);


drop trigger shndata.mr_ivtrg;
commit;

create trigger shndata.MR_IVTRG after after insert on shndata.MR_IVTRN referencing 
new as new_row for each row mode DB2ROW 


 begin 
 declare L_CNT decimal(1,0) default 0; 
 declare L_MATTP char(1); 
 
 declare END_TABLE int default 0; 
 
 declare C1 cursor for select COUNT(*) L_COUNT FROM shndata.MR_IVTR1
 where IVT_MKTTP = new_row.IVT_MKTTP and IVT_LADNO = new_row.IVT_LADNO AND IVT_PRDCD = new_row.IVT_PRDCD AND IVT_PKGTP = new_row.IVT_PKGTP;

 declare continue handler for not found 
 set END_TABLE = 1; 

 
	open C1;
	while END_TABLE = 0 DO 

	 fetch C1 into L_CNT; 
	 if L_CNT = 0 and new_row.IVT_SALTP ='04' then
	insert into shndata.mr_ivtr1(IVT_MKTTP,IVT_LADNO,IVT_PRDCD,IVT_PKGTP,IVT_LADDT,
    IVT_DORNO,IVT_INDNO,IVT_INVNO,IVT_INVDT,IVT_GINNO,IVT_SALTP,IVT_CNSCD,IVT_BYRCD,
    IVT_DSRCD,IVT_TMOCD,IVT_CURCD,IVT_LRYNO,IVT_CNTDS,IVT_LR_NO,IVT_LR_DT,IVT_PMDDT,
    IVT_CPTVL,IVT_ASSVL,IVT_DSCVL,IVT_PKFVL,IVT_INSVL,IVT_STXVL,IVT_EXCVL,IVT_INVVL,
    IVT_NETVL,IVT_LADRT,IVT_EXCRT,IVT_INVRT,IVT_PKGWT,IVT_LADQT,IVT_REQQT,
    IVT_INVQT,IVT_INVPK,IVT_AUTBY,IVT_DSTDS,IVT_STSFL,IVT_LUSBY,IVT_LUPDT,IVT_DTPCD,
    IVT_TSTFL,IVT_SLRFL,IVT_TSLNO,IVT_RSLNO,IVT_ADLNO,IVT_ADLDT,IVT_PRDDS,IVT_PRDTP,
    IVT_LOTRF,IVT_UOMCD,IVT_DORDT,IVT_LODDT,IVT_TRPCD,IVT_PORNO,IVT_PORDT,IVT_ZONCD,
    IVT_PMTTP,IVT_EXCCO,IVT_STXRT,IVT_STXCD,IVT_OCTRT,IVT_OCTCD,IVT_ALODT,IVT_TRNFL,
    IVT_FRTRT,IVT_SVCCD,IVT_SVCRT,IVT_EPIFL,IVT_RSNVL,IVT_CDCVL,IVT_DDCVL,IVT_TDCVL,
    IVT_DCMVL,IVT_TDCRF,IVT_SBSCD,IVT_EDCRT,IVT_EDCVL,IVT_EHCRT,IVT_EHCVL,IVT_SCHRT,
    IVT_TOTRT,IVT_PMTCD,IVT_CC1VL,IVT_CC1RF,IVT_CC2VL,IVT_CC2RF,IVT_CC3VL,IVT_CC3RF,IVT_FRTVL,IVT_CCLVL,
    IVT_COMVL,IVT_SLRQT,IVT_SLRRF,IVR_CRDVL,IVT_CRDVL,IVT_COPVL,IVT_BKGDT,IVT_CPRVL,
    IVT_TD1VL,IVT_TD2VL,IVT_TD3VL,IVT_TDMVL,IVT_LCNUM,IVT_LCDAT,IVT_UNLSQ,IVT_CSLNO,
    IVT_OCRVL,IVT_ODBVL,IVT_DSRTP) select IVT_MKTTP,IVT_LADNO,IVT_PRDCD,IVT_PKGTP,
    IVT_LADDT,IVT_DORNO,IVT_INDNO,IVT_INVNO,IVT_INVDT,IVT_GINNO,IVT_SALTP,IVT_CNSCD,
    IVT_BYRCD,IVT_DSRCD,IVT_TMOCD,IVT_CURCD,IVT_LRYNO,IVT_CNTDS,IVT_LR_NO,IVT_LR_DT,
    IVT_PMDDT,IVT_CPTVL,IVT_ASSVL,IVT_DSCVL,IVT_PKFVL,IVT_INSVL,IVT_STXVL,IVT_EXCVL,
    IVT_INVVL,IVT_NETVL,IVT_LADRT,IVT_EXCRT,IVT_INVRT,IVT_PKGWT,IVT_LADQT,
    IVT_REQQT,IVT_INVQT,IVT_INVPK,IVT_AUTBY,IVT_DSTDS,IVT_STSFL,IVT_LUSBY,IVT_LUPDT,
    IVT_DTPCD,IVT_TSTFL,IVT_SLRFL,IVT_TSLNO,IVT_RSLNO,IVT_ADLNO,IVT_ADLDT,IVT_PRDDS,
    IVT_PRDTP,IVT_LOTRF,IVT_UOMCD,IVT_DORDT,IVT_LODDT,IVT_TRPCD,IVT_PORNO,IVT_PORDT,
    IVT_ZONCD,IVT_PMTTP,IVT_EXCCO,IVT_STXRT,IVT_STXCD,IVT_OCTRT,IVT_OCTCD,IVT_ALODT,
    IVT_TRNFL,IVT_FRTRT,IVT_SVCCD,IVT_SVCRT,IVT_EPIFL,IVT_RSNVL,IVT_CDCVL,IVT_DDCVL,
    IVT_TDCVL,IVT_DCMVL,IVT_TDCRF,IVT_SBSCD,IVT_EDCRT,IVT_EDCVL,IVT_EHCRT,IVT_EHCVL,
    IVT_SCHRT,IVT_TOTRT,IVT_PMTCD,IVT_CC1VL,IVT_CC1RF,IVT_CC2VL,IVT_CC2RF,IVT_CC3VL,IVT_CC3RF,IVT_FRTVL,
    IVT_CCLVL,IVT_COMVL,IVT_SLRQT,IVT_SLRRF,IVR_CRDVL,IVT_CRDVL,IVT_COPVL,IVT_BKGDT,
    IVT_CPRVL,IVT_TD1VL,IVT_TD2VL,IVT_TD3VL,IVT_TDMVL,IVT_LCNUM,IVT_LCDAT,IVT_UNLSQ,
    IVT_CSLNO,IVT_OCRVL,IVT_ODBVL,IVT_DSRTP from shndata.mr_ivtrn where 
    ivt_mkttp = new_row.ivt_mkttp and ivt_ladno = new_row.ivt_ladno and 
    ivt_prdcd = new_row.ivt_prdcd and ivt_pkgtp = new_row.ivt_pkgtp;
  end if;
 fetch C1 into L_CNT; 
 end while; 
 close C1; 

end;

COMMIT;


SELECT * FROM SPLDATA.PR_LTMST WHERE LT_LOTNO ='11170441';


SELECT * FROM SPLDATA.FG_RCTRN WHERE RCT_LOTNO ='11170441';

SELECT * FROM SPLDATA.FG_ISTRN WHERE IST_LOTNO ='11170441';

SELECT SUM(IST_ISSQT) FROM SPLDATA.FG_ISTRN WHERE IST_LOTNO ='11170441';


























