/* Enter one or more SQL statements separated by semicolons */

CREATE TABLE SPLHIST.BK_PSLYR_J0506 LIKE SPLDATA.MM_PSLYR;
INSERT INTO SPLHIST.BK_PSLYR_J0506 SELECT * FROM SPLDATA.MM_PSLYR;
COMMIT;

CREATE TABLE SPLHIST.BK_YRPRC_J0506 LIKE SPLDATA.MM_YRPRC;
INSERT INTO SPLHIST.BK_YRPRC_J0506 SELECT * FROM SPLDATA.MM_YRPRC;

COMMIT;

SELECT * FROM SPLHIST.BK_PSLYR_J0506;
SELECT * FROM SPLHIST.BK_YRPRC_J0506;

SELECT SUM(YR_YCSVL) FROM SPLHIST.BK_YRPRC_J0506 WHERE YR_STRTP ='01';
SELECT SUM(YR_YCSVL) FROM SPLDATA.MM_YRPRC WHERE YR_STRTP ='01';

update spldata.mm_stprc set stp_crcqt =0,stp_crcvl =0,stp_cisqt =0,stp_cisvl =0,stp_cmrqt =0,stp_cmrvl =0,stp_csaqt =0,stp_csavl =0,stp_cstqt =0,stp_cstvl =0;

COMMIT;

SELECT ST_MDVQT,ST_MDVVL,STP_CMDQT,STP_CMDVL FROM SPLDATA.MM_STMST,SPLDATA.MM_STPRC WHERE ST_STRTP = STP_STRTP AND ST_MATCD = STP_MATCD AND ST_MDVQT >0;

/** iNITIALISING THE CUMMULATIVE VALUES IN MM_STPRC */

UPDATE SPLDATA.MM_STPRC SET STP_CRCQT =0,STP_CRCVL =0,STP_CISQT =0,STP_CISVL =0,STP_CMRQT =0,STP_CMRVL =0,STP_CSAQT=0,STP_CSAVL =0,STP_CSTQT =0,STP_CSTVL =0,STP_CMDQT =0,STP_CMDVL =0,STP_CMIQT =0,STP_CMIVL =0;

/**  UPDATING YEAR CLOSING STOCK / QTY AND YEAR CLOSING MODVAT QTY / VALUE IN OPENING OF STPRC */

update spldata.mm_stprc set stp_ycsvl = (select yr_ycsvl from spldata.mm_yrprc where yr_strtp = stp_strtp and yr_matcd = stp_matcd and yr_strtp in ('01','07','08')) where stp_strtp in ('01','07','08') ; 

update spldata.mm_stprc set stp_ycsQT = (select yr_ycsQT from spldata.mm_yrprc where yr_strtp = stp_strtp and yr_matcd = stp_matcd and yr_strtp in ('01','07','08')) where stp_strtp in ('01','07','08') ; 

UPDATE SPLDATA.MM_STPRC SET STP_YCMQT=(SELECT isnull(YR_YCMQT ,0) FROM SPLDATA.MM_YRPRC WHERE YR_STRTP=STP_STRTP AND YR_MATCD=STP_MATCD) WHERE STP_STRTP NOT IN ('04','09') AND STP_STRTP + STP_MATCD IN (SELECT B.YR_STRTP + B.YR_MATCD FROM SPLDATA.MM_YRPRC B);

UPDATE SPLDATA.MM_STPRC SET STP_YCMVL=(SELECT isnull(YR_YCMVL ,0) FROM SPLDATA.MM_YRPRC WHERE YR_STRTP=STP_STRTP AND YR_MATCD=STP_MATCD) WHERE STP_STRTP NOT IN ('04','09') AND STP_STRTP + STP_MATCD IN (SELECT B.YR_STRTP + B.YR_MATCD FROM SPLDATA.MM_YRPRC B);


UPDATE SPLDATA.MM_STPRC SET STP_YOSQT = STP_YCSQT,STP_YOSVL = STP_YCSVL,STP_YOMQT = STP_YCMQT,STP_YOMVL = STP_YCMVL WHERE STP_STRTP IN('01','07','08');

UPDATE SPLDATA.MM_STMST SET (ST_YOPST,ST_YOPVL) = (SELECT STP_YCSQT,STP_YCSVL FROM SPLDATA.MM_STPRC WHERE STP_STRTP = ST_STRTP AND STP_MATCD = ST_MATCD);

/** SETTING THE MONTH OPENING VALUES FOR FIRST MONTH PROCESSING

UPDATE SPLDATA.MM_STPRC SET STP_MORCQ = 0, STP_MORCV =0, STP_MOISQ =0,STP_MOISV =0,STP_MOMRQ =0,STP_MOMRV =0,STP_MOSAQ =0,STP_MOSAV =0,STP_MOSTQ =0,STP_MOSTV =0  WHERE STP_STRTP IN('01','07','08');

UPDATE SPLDATA.MM_STPRC SET STP_MOSQT = STP_YOSQT,STP_MOSVL = STP_YOSVL,STP_MOMQT = STP_YOMQT,STP_MOMVL = STP_YOMVL WHERE STP_STRTP IN('01','07','08');

COMMIT;

/**  ANOTHER BACKUP IN SPLDATA */

create table SPLDATA.BK_YRPRC_J0506 LIKE SPLDATA.MM_YRPRC;
INSERT INTO SPLDATA.BK_YRPRC_J0506 SELECT * FROM SPLDATA.MM_YRPRC;

CREATE TABLE SPLDATA.BK_PSLYR_J0506 LIKE SPLDATA.MM_PSLYR;
INSERT INTO SPLDATA.BK_PSLYR_J0506 SELECT * FROM  SPLDATA.MM_PSLYR;
COMMIT;

SELECT SUM(YR_YCSVL) FROM SPLDATA.BK_YRPRC_J0506 WHERE YR_STRTP ='01';
SELECT SUM(YR_YCSVL) FROM SPLDATA.MM_YRPRC WHERE YR_STRTP ='01';
SELECT SUM(STP_YOSVL) FROM SPLDATA.MM_STPRC WHERE STP_STRTP ='01';


/** NOW DO THE YEARLY PROCESSING FOR A  MONTH AND UPDATE OTHER VALUES */

UPDATE SPLDATA.MM_STPRC SET STP_MORCQ = 0, STP_MORCV =0, STP_MOISQ =0,STP_MOISV =0,STP_MOMRQ =0,STP_MOMRV =0,STP_MOSAQ =0,STP_MOSAV =0,STP_MOSTQ =0,STP_MOSTV =0  WHERE STP_STRTP IN('01','07','08');
