--  Generate SQL 
--  Version:                   	V5R3M0 040528 
--  Generated on:              	23/07/08 20:35:03 
--  Relational Database:       	SPLWS01 
--  Standards Option:          	DB2 UDB iSeries 
  
SET PATH "QSYS","QSYS2","FIMS" ; 
 drop procedure spldata.setHML;
commit;
CREATE PROCEDURE SPLDATA.SETHML (
                    IN LP_CMPCD char(2), 
	IN P_CHRSTRTP CHAR(2) , 
	IN P_INTH_VAL INTEGER , 
	IN P_INTM_VAL INTEGER ) 
	LANGUAGE SQL 
	SPECIFIC SPLDATA.SETHML 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	P1 : 
		BEGIN 
		DECLARE END_TABLE INT DEFAULT 0 ; 
		DECLARE DCMYCLRT DECIMAL ( 12 , 2 ) ; 
		DECLARE DCMPPORT DECIMAL ( 12 , 2 ) ; 
		DECLARE STRMMSBS CHAR ( 6 ) ; 
		DECLARE STRSTRTP CHAR ( 2 ) ; 
		DECLARE STRMATCD CHAR ( 10 ) ; 
		DECLARE STRTAG CHAR ( 1 ) ; 
		 
		 
		DECLARE C_DATA CURSOR FOR SELECT ST_MMSBS , ST_STRTP , ST_MATCD , STP_YCLRT , ST_PPOVL FROM SPLDATA . MM_STMST , SPLDATA . MM_STPRC WHERE ST_CMPCD = LP_CMPCD and ST_STRTP = P_CHRSTRTP AND ST_MMSBS = STP_MMSBS AND ST_STRTP = STP_STRTP AND ST_MATCD = STP_MATCD ORDER BY ST_MATCD ; 
		 
		 
		DECLARE CONTINUE HANDLER FOR NOT FOUND 
		SET END_TABLE = 1 ; 
	  
		UPDATE SPLDATA . MM_STMST SET ST_HMLFL = '' WHERE ST_CMPCD = LP_CMPCD and ST_STRTP = P_CHRSTRTP ; 
		 
		OPEN C_DATA ; 
		FETCH C_DATA INTO STRMMSBS , STRSTRTP , STRMATCD , DCMYCLRT , DCMPPORT ; 
		 
		WHILE END_TABLE = 0 DO 
	  
		SET STRTAG = 'L' ; 
		IF ( DCMYCLRT >= P_INTH_VAL ) THEN 
			SET STRTAG = 'H' ; 
		ELSEIF ( DCMYCLRT >= P_INTM_VAL ) THEN 
			SET STRTAG = 'M' ; 
		END IF ; 
		 
		UPDATE SPLDATA . MM_STMST SET ST_HMLFL = STRTAG WHERE ST_CMPCD = LP_CMPCD and ST_MMSBS = STRMMSBS AND ST_STRTP = STRSTRTP AND ST_MATCD = STRMATCD ; 
		FETCH C_DATA INTO STRMMSBS , STRSTRTP , STRMATCD , DCMYCLRT , DCMPPORT ; 
		END WHILE ; 
		CLOSE C_DATA ; 
		COMMIT ; 
		END P1  ; 
commit;

