drop trigger spldata.mr_ivtrg;
commit;

create trigger spldata.MR_IVTRG after update of IVT_INVNO on spldata.MR_IVTRN referencing 
new as new_row old as old_row for each row mode DB2ROW 

 begin 
 declare L_CNT decimal(1,0) default 0; 
 declare L_MATTP char(1); 
 
 declare END_TABLE int default 0; 
 
 declare C1 cursor for select COUNT(*) L_COUNT FROM spldata.MR_IVTR1
 where IVT_CMPCD = new_row.IVT_CMPCD and IVT_MKTTP = new_row.IVT_MKTTP and IVT_LADNO = new_row.IVT_LADNO AND IVT_PRDCD = new_row.IVT_PRDCD AND IVT_PKGTP = new_row.IVT_PKGTP;

 declare continue handler for not found 
 set END_TABLE = 1; 

 
	open C1;
	while END_TABLE = 0 DO 

	 fetch C1 into L_CNT; 
	 if L_CNT = 0 and new_row.IVT_SALTP ='04' then
	insert into spldata.mr_ivtr1(IVT_CMPCD,IVT_MKTTP,IVT_LADNO,IVT_PRDCD,IVT_PKGTP,IVT_LADDT,
    IVT_DORNO,IVT_INDNO,IVT_INVNO,IVT_INVDT,IVT_GINNO,IVT_SALTP,IVT_CNSCD,IVT_BYRCD,
    IVT_DSRCD,IVT_TMOCD,IVT_CURCD,IVT_LRYNO,IVT_CNTDS,IVT_LR_NO,IVT_LR_DT,IVT_PMDDT,
    IVT_CPTVL,IVT_ASSVL,IVT_DSCVL,IVT_PKFVL,IVT_INSVL,IVT_STXVL,IVT_EXCVL,IVT_INVVL,
    IVT_NETVL,IVT_LADRT,IVT_EXCRT,IVT_INVRT,IVT_PKGWT,IVT_LADQT,IVT_REQQT,
    IVT_INVQT,IVT_INVPK,IVT_AUTBY,IVT_DSTDS,IVT_STSFL,IVT_LUSBY,IVT_LUPDT,IVT_DTPCD,
    IVT_TSTFL,IVT_SLRFL,IVT_TSLNO,IVT_RSLNO,IVT_ADLNO,IVT_ADLDT,IVT_PRDDS,IVT_PRDTP,
    IVT_LOTRF,IVT_UOMCD,IVT_DORDT,IVT_LODDT,IVT_TRPCD,IVT_PORNO,IVT_PORDT,IVT_ZONCD,
    IVT_PMTTP,IVT_EXCCO,IVT_STXRT,IVT_STXCD,IVT_OCTRT,IVT_OCTCD,IVT_ALODT,IVT_TRNFL,
    IVT_FRTRT,IVT_SVCCD,IVT_SVCRT,IVT_EPIFL,IVT_RSNVL,IVT_CDCVL,IVT_DDCVL,IVT_TDCVL,
    IVT_DCMVL,IVT_TDCRF,IVT_SBSCD,IVT_EDCRT,IVT_EDCVL,IVT_EHCRT,IVT_EHCVL,IVT_SCHRT,
    IVT_TOTRT,IVT_PMTCD,IVT_CC1VL,IVT_CC1RF,IVT_CC2VL,IVT_CC2RF,IVT_CC3VL,IVT_CC3RF,IVT_FRTVL,IVT_CCLVL,
    IVT_COMVL,IVT_SLRQT,IVT_SLRRF,IVR_CRDVL,IVT_CRDVL,IVT_COPVL,IVT_BKGDT,IVT_CPRVL,
    IVT_TD1VL,IVT_TD2VL,IVT_TD3VL,IVT_TDMVL,IVT_LCNUM,IVT_LCDAT,IVT_UNLSQ,IVT_CSLNO,
    IVT_OCRVL,IVT_ODBVL,IVT_DSRTP) select IVT_CMPCD,IVT_MKTTP,IVT_LADNO,IVT_PRDCD,IVT_PKGTP,
    IVT_LADDT,IVT_DORNO,IVT_INDNO,IVT_INVNO,IVT_INVDT,IVT_GINNO,IVT_SALTP,IVT_CNSCD,
    IVT_BYRCD,IVT_DSRCD,IVT_TMOCD,IVT_CURCD,IVT_LRYNO,IVT_CNTDS,IVT_LR_NO,IVT_LR_DT,
    IVT_PMDDT,IVT_CPTVL,IVT_ASSVL,IVT_DSCVL,IVT_PKFVL,IVT_INSVL,IVT_STXVL,IVT_EXCVL,
    IVT_INVVL,IVT_NETVL,IVT_LADRT,IVT_EXCRT,IVT_INVRT,IVT_PKGWT,IVT_LADQT,
    IVT_REQQT,IVT_INVQT,IVT_INVPK,IVT_AUTBY,IVT_DSTDS,IVT_STSFL,IVT_LUSBY,IVT_LUPDT,
    IVT_DTPCD,IVT_TSTFL,IVT_SLRFL,IVT_TSLNO,IVT_RSLNO,IVT_ADLNO,IVT_ADLDT,IVT_PRDDS,
    IVT_PRDTP,IVT_LOTRF,IVT_UOMCD,IVT_DORDT,IVT_LODDT,IVT_TRPCD,IVT_PORNO,IVT_PORDT,
    IVT_ZONCD,IVT_PMTTP,IVT_EXCCO,IVT_STXRT,IVT_STXCD,IVT_OCTRT,IVT_OCTCD,IVT_ALODT,
    IVT_TRNFL,IVT_FRTRT,IVT_SVCCD,IVT_SVCRT,IVT_EPIFL,IVT_RSNVL,IVT_CDCVL,IVT_DDCVL,
    IVT_TDCVL,IVT_DCMVL,IVT_TDCRF,IVT_SBSCD,IVT_EDCRT,IVT_EDCVL,IVT_EHCRT,IVT_EHCVL,
    IVT_SCHRT,IVT_TOTRT,IVT_PMTCD,IVT_CC1VL,IVT_CC1RF,IVT_CC2VL,IVT_CC2RF,IVT_CC3VL,IVT_CC3RF,IVT_FRTVL,
    IVT_CCLVL,IVT_COMVL,IVT_SLRQT,IVT_SLRRF,IVR_CRDVL,IVT_CRDVL,IVT_COPVL,IVT_BKGDT,
    IVT_CPRVL,IVT_TD1VL,IVT_TD2VL,IVT_TD3VL,IVT_TDMVL,IVT_LCNUM,IVT_LCDAT,IVT_UNLSQ,
    IVT_CSLNO,IVT_OCRVL,IVT_ODBVL,IVT_DSRTP from spldata.mr_ivtrn where 
    IVT_CMPCD = new_row.IVT_CMPCD and ivt_mkttp = new_row.ivt_mkttp and ivt_ladno = new_row.ivt_ladno and 
    ivt_prdcd = new_row.ivt_prdcd and ivt_pkgtp = new_row.ivt_pkgtp;
  end if;
  if L_CNT > 0 and new_row.IVT_SALTP ='04' then
	update spldata.mr_ivtr1 a set (IVT_INVNO,IVT_LADDT,
    IVT_DORNO,IVT_INDNO,IVT_INVDT,IVT_GINNO,IVT_SALTP,IVT_CNSCD,IVT_BYRCD,
    IVT_DSRCD,IVT_TMOCD,IVT_CURCD,IVT_LRYNO,IVT_CNTDS,IVT_LR_NO,IVT_LR_DT,IVT_PMDDT,
    IVT_CPTVL,IVT_ASSVL,IVT_DSCVL,IVT_PKFVL,IVT_INSVL,IVT_STXVL,IVT_EXCVL,IVT_INVVL,
    IVT_NETVL,IVT_LADRT,IVT_EXCRT,IVT_INVRT,IVT_PKGWT,IVT_LADQT,IVT_REQQT,
    IVT_INVQT,IVT_INVPK,IVT_AUTBY,IVT_DSTDS,IVT_STSFL,IVT_LUSBY,IVT_LUPDT,IVT_DTPCD,
    IVT_TSTFL,IVT_SLRFL,IVT_TSLNO,IVT_RSLNO,IVT_ADLNO,IVT_ADLDT,IVT_PRDDS,IVT_PRDTP,
    IVT_LOTRF,IVT_UOMCD,IVT_DORDT,IVT_LODDT,IVT_TRPCD,IVT_PORNO,IVT_PORDT,IVT_ZONCD,
    IVT_PMTTP,IVT_EXCCO,IVT_STXRT,IVT_STXCD,IVT_OCTRT,IVT_OCTCD,IVT_ALODT,IVT_TRNFL,
    IVT_FRTRT,IVT_SVCCD,IVT_SVCRT,IVT_EPIFL,IVT_RSNVL,IVT_CDCVL,IVT_DDCVL,IVT_TDCVL,
    IVT_DCMVL,IVT_TDCRF,IVT_SBSCD,IVT_EDCRT,IVT_EDCVL,IVT_EHCRT,IVT_EHCVL,IVT_SCHRT,
    IVT_TOTRT,IVT_PMTCD,IVT_CC1VL,IVT_CC1RF,IVT_CC2VL,IVT_CC2RF,IVT_CC3VL,IVT_CC3RF,IVT_FRTVL,IVT_CCLVL,
    IVT_COMVL,IVT_SLRQT,IVT_SLRRF,IVR_CRDVL,IVT_CRDVL,IVT_COPVL,IVT_BKGDT,IVT_CPRVL,
    IVT_TD1VL,IVT_TD2VL,IVT_TD3VL,IVT_TDMVL,IVT_LCNUM,IVT_LCDAT,IVT_UNLSQ,IVT_CSLNO,
    IVT_OCRVL,IVT_ODBVL,IVT_DSRTP) = (select  
    b.IVT_INVNO,b.IVT_LADDT,b.IVT_DORNO,b.IVT_INDNO,b.IVT_INVDT,b.IVT_GINNO,b.IVT_SALTP,b.IVT_CNSCD,
    b.IVT_BYRCD,b.IVT_DSRCD,b.IVT_TMOCD,b.IVT_CURCD,b.IVT_LRYNO,b.IVT_CNTDS,b.IVT_LR_NO,b.IVT_LR_DT,
    b.IVT_PMDDT,b.IVT_CPTVL,b.IVT_ASSVL,b.IVT_DSCVL,b.IVT_PKFVL,b.IVT_INSVL,b.IVT_STXVL,b.IVT_EXCVL,
    b.IVT_INVVL,b.IVT_NETVL,b.IVT_LADRT,b.IVT_EXCRT,b.IVT_INVRT,b.IVT_PKGWT,b.IVT_LADQT,
    b.IVT_REQQT,b.IVT_INVQT,b.IVT_INVPK,b.IVT_AUTBY,b.IVT_DSTDS,b.IVT_STSFL,b.IVT_LUSBY,b.IVT_LUPDT,
    b.IVT_DTPCD,b.IVT_TSTFL,b.IVT_SLRFL,b.IVT_TSLNO,b.IVT_RSLNO,b.IVT_ADLNO,b.IVT_ADLDT,b.IVT_PRDDS,
    b.IVT_PRDTP,b.IVT_LOTRF,b.IVT_UOMCD,b.IVT_DORDT,b.IVT_LODDT,b.IVT_TRPCD,b.IVT_PORNO,b.IVT_PORDT,
    b.IVT_ZONCD,b.IVT_PMTTP,b.IVT_EXCCO,b.IVT_STXRT,b.IVT_STXCD,b.IVT_OCTRT,b.IVT_OCTCD,b.IVT_ALODT,
    b.IVT_TRNFL,b.IVT_FRTRT,b.IVT_SVCCD,b.IVT_SVCRT,b.IVT_EPIFL,b.IVT_RSNVL,b.IVT_CDCVL,b.IVT_DDCVL,
    b.IVT_TDCVL,b.IVT_DCMVL,b.IVT_TDCRF,b.IVT_SBSCD,b.IVT_EDCRT,b.IVT_EDCVL,b.IVT_EHCRT,b.IVT_EHCVL,
    b.IVT_SCHRT,b.IVT_TOTRT,b.IVT_PMTCD,b.IVT_CC1VL,b.IVT_CC1RF,b.IVT_CC2VL,b.IVT_CC2RF,b.IVT_CC3VL,b.IVT_CC3RF,b.IVT_FRTVL,
    b.IVT_CCLVL,b.IVT_COMVL,b.IVT_SLRQT,b.IVT_SLRRF,IVR_CRDVL,b.IVT_CRDVL,b.IVT_COPVL,b.IVT_BKGDT,
    b.IVT_CPRVL,b.IVT_TD1VL,b.IVT_TD2VL,b.IVT_TD3VL,b.IVT_TDMVL,b.IVT_LCNUM,b.IVT_LCDAT,b.IVT_UNLSQ,
    b.IVT_CSLNO,b.IVT_OCRVL,b.IVT_ODBVL,b.IVT_DSRTP from spldata.mr_ivtrn b where 
    a.ivt_CMPCD = b.IVT_CMPCD and a.ivt_mkttp = b.ivt_mkttp and a.ivt_ladno = b.ivt_ladno and  a.ivt_prdcd = b.ivt_prdcd and a.ivt_pkgtp = b.ivt_pkgtp)  where 
    a.ivt_CMPCD = new_row.IVT_CMPCD and a.ivt_mkttp = new_row.ivt_mkttp and a.ivt_ladno = new_row.ivt_ladno and 
 a.ivt_prdcd = new_row.ivt_prdcd and a.ivt_pkgtp = new_row.ivt_pkgtp;
  end if;
 fetch C1 into L_CNT; 
 end while; 
 close C1; 

end;

COMMIT;

select * from spldata.mr_ivtrn where ivt_saltp='04';
