drop trigger SPLDATA.updPTMST;
commit;

create trigger SPLDATA.updPTMST after update on SPLDATA.CO_PTMST referencing 
new as new_row for each row mode DB2ROW  
begin 
update SHNDATA.co_ptmst set (PT_PRTNM,PT_SHRNM,PT_GRPCD,PT_ADR01,PT_ADR02,PT_ADR03,
PT_ADR04,PT_PINCD,PT_CTYNM,PT_STACD,PT_CNTCD,PT_CONNM,PT_TEL01,PT_TEL02,PT_EMLRF,
PT_FAXNO,PT_STXNO,PT_STXDT,PT_CLSCD,PT_SCRCD,PT_CSTNO,PT_CSTDT,PT_ECCNO,PT_ITPNO, 
PT_EXCNO,PT_RNGDS,PT_DIVDS,PT_CLLDS,PT_ZONCD,PT_TRNCD,PT_TSTFL,PT_DSTCD,PT_MOBNO,PT_COWEB,PT_EMLPR,PT_EMLMR,PT_EMLAC,PT_DSRCD,
PT_DOCRF,PT_APRDT,PT_EVLDT,PT_TINNO,PT_TINDT,PT_VATNO,PT_VATDT,PT_CNSRF) = (select PT_PRTNM,PT_SHRNM,PT_GRPCD,PT_ADR01,PT_ADR02,PT_ADR03,
PT_ADR04,PT_PINCD,PT_CTYNM,PT_STACD,PT_CNTCD,PT_CONNM,PT_TEL01,PT_TEL02,PT_EMLRF,
PT_FAXNO,PT_STXNO,PT_STXDT,PT_CLSCD,PT_SCRCD,PT_CSTNO,PT_CSTDT,PT_ECCNO,PT_ITPNO, 
PT_EXCNO,PT_RNGDS,PT_DIVDS,PT_CLLDS,PT_ZONCD,PT_TRNCD,PT_TSTFL,PT_DSTCD,PT_MOBNO,PT_COWEB,PT_EMLPR,PT_EMLMR,PT_EMLAC,PT_DSRCD,
PT_DOCRF,PT_APRDT,PT_EVLDT,PT_TINNO,PT_TINDT,PT_VATNO,PT_VATDT,PT_CNSRF from SPLDATA.co_ptmst where pt_prttp = new_row.pt_prttp and pt_prtcd = new_row.pt_prtcd) 
where pt_prttp = new_row.pt_prttp and pt_prtcd = new_row.pt_prtcd; 
END;
commit;


