--IND

DELETE FROM SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP  LIKE 'MR%%IND'
COMMIT;

DELETE FROM  SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' ;AND SUBSTRING(CMT_CODCD,1,1) ='7';

SELECT * FROM  SPLDATA.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' AND SUBSTRING(CMT_CODCD,1,1) ='7';

INSERT INTO SPLTEST.CO_CDTRN SELECT * FROM  SPLDATA.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%IND' AND SUBSTRING(CMT_CODCD,4,1) ='7';

COMMIT;

SELECT * FROM SPLDATA.CO_CDTRN WHERE CMT_CGSTP LIKE 'MR%';
SELECT CMT_CGSTP,CMT_CODCD,SUBSTRING(CMT_CODCD,1,3),SUBSTRING(CMT_CODCD,4,1),CMT_CCSVL FROM SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%IND' AND SUBSTRING(CMT_CODCD,4,1) ='8';

UPDATE SPLTEST.CO_CDTRN SET CMT_CODCD =SUBSTRING(CMT_CODCD,1,3) + '8',CMT_CCSVL ='0000'  WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%IND' AND SUBSTRING(CMT_CODCD,4,1) ='7';

INSERT INTO SPLDATA.CO_CDTRN SELECT * FROM SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%IND' AND SUBSTRING(CMT_CODCD,4,1) ='8';
COMMIT;

-- DOR

INSERT INTO SPLTEST.CO_CDTRN SELECT * FROM  SPLDATA.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' AND SUBSTRING(CMT_CODCD,1,1) ='7';

COMMIT;

SELECT CMT_CODCD,SUBSTRING(CMT_CODCD,1,1), SUBSTRING(CMT_CODCD,2,2) FROM  SPTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' AND SUBSTRING(CMT_CODCD,1,1) ='7';

UPDATE SPLTEST.CO_CDTRN SET CMT_CODCD = WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' AND SUBSTRING(CMT_CODCD,1,1) ='7';


SELECT CMT_CODCD,SUBSTRING(CMT_CODCD,1,1),SUBSTRING(CMT_CODCD,2,2),CMT_CCSVL FROM  SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' ;AND SUBSTRING(CMT_CODCD,1,1) ='7';

UPDATE SPLTEST.CO_CDTRN SET CMT_CODCD = '8' + SUBSTRING(CMT_CODCD,2,2),CMT_CCSVL ='00000' WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' AND SUBSTRING(CMT_CODCD,1,1) ='7';

COMMIT;

INSERT INTO SPLDATA.CO_CDTRN SELECT * FROM  SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE 'MR%%DOR' ;

COMMIT;

SELECT * FROM SPLTEST.CO_CDTRN WHERE CMT_CGMTP ='DOC' AND CMT_CGSTP LIKE '%DOR'