/* Enter one or more SQL statements separated by semicolons */
SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100394';
SELECT * FROM SPLDATA.MM_STPRC WHERE ;

delete FROM SPLTEST.MM_STPRC;
COMMIT;

INSERT INTO SPLTEST.MM_STPRC SELECT * FROM SPLDATA.MM_STPRC;
SELECT GR_PORNO,GR_BILRF FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100394';
SELECT * FROM SPLDATA.CO_TXDOC WHERE TX_DOCNO = '62100267';
SELECT * FROM SPLDATA.CO_TXDOC WHERE TX_DOCNO = '60100706';

SELECT * FROM SPLDATA.MM_STPRC WHERE STP_STRTP ='01' AND STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100394');

SELECT * FROM SPLTEST.MM_STPRC WHERE STP_STRTP ='01' AND STP_MATCD IN (SELECT STP_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100394');

SELECT STP_MATCD,isnull(STP_YOSVL,0) L_YOSVL , (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) L_RCTVL, (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_ISSVL, isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_CALVL ,isnull(STP_YCSVL,0) L_YCSVL FROM SPLDATA.MM_STPRC WHERE ROUND(isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)),0)  <> ROUND(isnull(STP_YCSVL,0),0) AND STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100394');

SELECT STP_MATCD,isnull(STP_YOSVL,0) L_YOSVL , (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) L_RCTVL, (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_ISSVL, isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_CALVL ,isnull(STP_YCSVL,0) L_YCSVL FROM SPLDATA.MM_STPRC WHERE STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100394');


SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100527';

SELECT STP_MATCD,isnull(STP_YOSVL,0) L_YOSVL , (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) L_RCTVL, (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_ISSVL, isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_CALVL ,isnull(STP_YCSVL,0) L_YCSVL FROM SPLDATA.MM_STPRC WHERE STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100527');


SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100472';

SELECT STP_MATCD,isnull(STP_YOSVL,0) L_YOSVL , (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) L_RCTVL, (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_ISSVL, isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_CALVL ,isnull(STP_YCSVL,0) L_YCSVL FROM SPLDATA.MM_STPRC WHERE STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100472');

SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100495';

SELECT STP_MATCD,isnull(STP_YOSVL,0) L_YOSVL , (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) L_RCTVL, (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_ISSVL, isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_CALVL ,isnull(STP_YCSVL,0) L_YCSVL FROM SPLDATA.MM_STPRC WHERE STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100495');

SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100496';

SELECT STP_MATCD,isnull(STP_YOSVL,0) L_YOSVL , (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) L_RCTVL, (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_ISSVL, isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_CALVL ,isnull(STP_YCSVL,0) L_YCSVL FROM SPLDATA.MM_STPRC WHERE STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100496');

SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100482';
SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100499'
SELECT * FROM SPLDATA.MM_GRMST WHERE  GR_GRNNO ='63100486';;
SELECT STP_MATCD,isnull(STP_YOSVL,0) L_YOSVL , (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) L_RCTVL, (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_ISSVL, isnull(STP_YOSVL,0) + (isnull(STP_CRCVL,0) +isnull(STP_CSAVL,0)) - (isnull(STP_CISVL,0) -isnull(STP_CMRVL,0)) L_CALVL ,isnull(STP_YCSVL,0) L_YCSVL FROM SPLDATA.MM_STPRC WHERE STP_MATCD IN (SELECT GR_MATCD FROM SPLDATA.MM_GRMST WHERE GR_STRTP ='01' AND GR_GRNNO ='63100490');
