--  Generate SQL 
--  Version:                   	V5R3M0 040528 
--  Generated on:              	02/06/09 11:48:14 
--  Relational Database:       	SPLWS01 
--  Standards Option:          	DB2 UDB iSeries 
drop TRIGGER SPLDATA.QSYS_TRIG_SPLDATA____HR_LVTRN___000001;
commit;

CREATE TRIGGER SPLDATA.QSYS_TRIG_SPLDATA____HR_LVTRN___000001 
	AFTER UPDATE OF LVT_STSFL ON SPLDATA.HR_LVTRN 
	REFERENCING OLD AS OLD_ROW 
	NEW AS NEW_ROW 
	FOR EACH ROW 
	MODE DB2ROW 
	BEGIN 
	  
	  
	IF NEW_ROW . LVT_STSFL IN ( '2' , '3' ) AND OLD_ROW . LVT_STSFL IN ( '1' , '8' , '9' ) THEN 
	  
	IF NEW_ROW . LVT_LVECD = 'CL' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDCL = SPLDATA . HR_EPMST . EP_YTDCL - NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	IF NEW_ROW . LVT_LVECD = 'PL' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDPL = SPLDATA . HR_EPMST . EP_YTDPL - NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	IF NEW_ROW . LVT_LVECD = 'SL' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDSL = SPLDATA . HR_EPMST . EP_YTDSL - NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	IF NEW_ROW . LVT_LVECD = 'RH' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDRH = SPLDATA . HR_EPMST . EP_YTDRH - NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	  
	  
	END IF ; 
	  
	IF ( NEW_ROW . LVT_STSFL = 'X' AND OLD_ROW . LVT_STSFL IN ( '2' , '3' ) ) THEN 
	  
	IF OLD_ROW . LVT_LVECD = 'CL' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDCL = SPLDATA . HR_EPMST . EP_YTDCL + NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	IF OLD_ROW . LVT_LVECD = 'PL' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDPL = SPLDATA . HR_EPMST . EP_YTDPL + NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	IF OLD_ROW . LVT_LVECD = 'SL' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDSL = SPLDATA . HR_EPMST . EP_YTDSL + NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	IF OLD_ROW . LVT_LVECD = 'RH' THEN 
	UPDATE SPLDATA . HR_EPMST SET EP_YTDRH = SPLDATA . HR_EPMST . EP_YTDRH + NEW_ROW . LVT_LVEQT WHERE SPLDATA . HR_EPMST . EP_HRSBS = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_EPMST . EP_EMPNO = NEW_ROW . LVT_EMPNO ; 
	END IF ; 
	  
	  
	END IF ; 
	IF NEW_ROW . LVT_STSFL IN ( '2' , '3' , 'X' ) THEN 
	  
	UPDATE SPLDATA . HR_SSTRN SET SS_LVECD = NEW_ROW . LVT_LVECD WHERE SPLDATA . HR_SSTRN . SS_SBSCD = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_SSTRN . SS_EMPNO = NEW_ROW . LVT_EMPNO AND SPLDATA . HR_SSTRN . SS_WRKDT = NEW_ROW . LVT_LVEDT ; 
	UPDATE SPLDATA . HR_SWMST SET SW_LVECD = NEW_ROW . LVT_LVECD WHERE SPLDATA . HR_SWMST . SW_SBSCD = NEW_ROW . LVT_SBSCD AND SPLDATA . HR_SWMST . SW_EMPNO = NEW_ROW . LVT_EMPNO AND SPLDATA . HR_SWMST . SW_WRKDT = NEW_ROW . LVT_LVEDT ; 
	END IF ; 
	  
	END  ;
